language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION="2.1"

before_script:
  - composer self-update
  - composer --version
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer install -n --dev --prefer-source

script: phpunit --coverage-text --configuration phpunit.xml.dist
